# Example XO-Server configuration.

# This file is automatically looking for at the following places:
# - `$HOME/.config/xo-server/config.yaml`
# - `/etc/xo-server/config.yaml`
#
# The first entries have priority.

# Note: paths are relative to the configuration file.

#=====================================================================

# It may be necessary to run XO-Server as a privileged user (e.g.
# `root`) for instance to allow the HTTP server to listen on a
# [privileged ports](http://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html).
#
# To avoid security issues, XO-Server can drop its privileges by
# changing the user and the group is running with.
#
# Note: XO-Server will change them just after reading the
# configuration.

# User to run XO-Server as.
#
# Note: The user can be specified using either its name or its numeric
# identifier.
#
# Default: undefined
#user: 'nobody'

# Group to run XO-Server as.
#
# Note: The group can be specified using either its name or its
# numeric identifier.
#
# Default: undefined
#group: 'nogroup'

#=====================================================================

# Configuration of the embedded HTTP server.
http:

  # Hosts & ports on which to listen.
  #
  # By default, the server listens on 0.0.0.0:80.
  listen:
    # Basic HTTP.
    -
      # Address on which the server is listening on.
      #
      # Sets it to '127.0.0.1' to listen only on the local host.
      #
      # Default: '0.0.0.0' (all addresses)
      #hostname: '127.0.0.1'

      # Port on which the server is listening on.
      #
      # Default: undefined
      port: 8080


  # List of files/directories which will be served.
  mounts:
    '/': '/app/xo-web/dist/'

#=====================================================================

# Connection to the Redis server.
redis:
    # Syntax: tcp://[db[:password]@]hostname[:port]
    #
    # Default: tcp://localhost:6379
    #uri: ''

# Directory containing the database of XO.
# Currently used for logs.
#
# Default: '/var/lib/xo-server/data'
datadir: '/app/data'
